print("Welcome to Mufakose")
print("Hello World")
print("I Love Sadza")
print("Actually I don't love Sadza, ndorida from time to time, maybe kana ndine nzara")
print("I Love my familly")
print("I Love Kelly")
print("Shamwari nzangu ndizvozvo,NO HOMO")
print("Need to have millions when l reach 25")
print("Need to keep working hard")
print("Need to have a muscular build muna September")
